### ISSUE TITLE
Jar doesn't find main method

### ISSUE THREAD

**Issue by Zethson** [teikitel/scala-spring-shell#1]
Hi,

I build the jar using sbt package.
When running the jar I get:
```
Error: Main method not found in class com.example.commands.DemoShellApplication, please define the main method as:
   public static void main(String[] args)
or a JavaFX application class must extend javafx.application.Application

```

How did you build the working jar?

Thanks!

**Comment by teikitel** [comment]
Easiest way is to import it in IntelliJ with Scala plugin installed and run the main class directly.

Just pushed a fix on Main object to make it runnable with sbt : 
```
sbt package
sbt run

```

**Comment by Zethson** [comment]
But that's not a distributable jar. 

I want to create a shareable jar such that other people can use solely the jar to run the program. This is a standard procedure.

Currently it requires the complete code and sbt installed.

**Comment by teikitel** [comment]
You can generate a FAT JAR using sbt-assembly which will allow you to share your JAR.
Depending on your runtime env you can even choose what dependencies you want to include/exclude from that JAR.

It is not utterly difficult but I do not have more time to spend on this so I'll push something to help you if I have time.

**Comment by Zethson** [comment]
I am well aware of fat jars, but never could get them working with this specific setup. Hence my notorious questions.

However, I have now finally a working version with sbt-native-packaging, which is exactly what I wanted.
In case you are interested: 
[Spring Shell Scala](https://github.com/Zethson/spring-shell2-scala)

Nevertheless, thank you very much for your patience and efforts!

**Comment by teikitel** [comment]
Yes sbt-native-packaging works as well.

You're welcome, cheers !
